apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  releaseName: alloy
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: alloy
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: alloy-values
      valuesKey: values.yaml
