apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: grafana
      version: "10.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: grafana-values
      valuesKey: values.yaml
