apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  releaseName: loki
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: loki
      version: "10.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: loki
      valuesKey: values.yaml
