apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-read
  namespace: monitoring
rules:
  - apiGroups: ["loki.grafana.com"]
    resources: ["logs"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-loki-read
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: monitoring
roleRef:
  kind: Role
  name: loki-read
  apiGroup: rbac.authorization.k8s.io
