apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ./helm/repository.yaml
  - ./resources/namespace.yaml
  - ./resources/release.yaml
  - ./resources/cluster-issuer.yaml