apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: step-ca
resources:
  - ./helm/repository.yaml
  - ./resources/namespace.yaml
  - ./resources/release.yaml
  - ./secrets/authority.yaml
  - ./secrets/config.yaml