## reconcile crds in any order, as they wont be dependent on eachother

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services-crds
  namespace: flux-system
spec:
  interval: 1m
  path: ./services/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: repo
  timeout: 1m
  wait: true
  dependsOn:
    - name: services-core-cf-issuer
