apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobalt
  namespace: cobalt
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cobalt
  template:
    metadata:
      labels:
        app: cobalt
    spec:
      containers:
        - name: cobalt
          image: ghcr.io/imputnet/cobalt:staging
          ports:
            - containerPort: 9000
          env:
            - name: API_URL
              value: https://cobalt.yyuemii.co
            - name: COOKIE_PATH
              value: /app/cookies.json
            - name: TURNSTILE_SITEKEY
              valueFrom:
                secretKeyRef:
                  name: turnstile
                  key: username
            - name: TURNSTILE_SECRET
              valueFrom:
                secretKeyRef:
                  name: turnstile
                  key: credential
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: turnstile
                  key: secret
          volumeMounts:
            - name: cookies
              mountPath: /app/cookies.json
              subPath: cookies.json
              readOnly: true
      volumes:
        - name: cookies
          secret:
            secretName: cookies