apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: whoami
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/whoami
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  resources:
    - ./resources/namespace.yaml
    - ./resources/deployment.yaml
    - ./resources/deployment.yaml