apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  interval: 1h
  timeout: 5m
  install:
    crds: Create
    remediation:
      retries: 5
  upgrade:
    crds: Create
  chart:
    spec:
      chart: external-secrets
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      interval: 1h
  values:
    installCRDs: true
