apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 1h
  values:
    installCRDs: true
extraVolumes:
  - name: ca-volume
    secret:
      secretName: step-ca-certs
extraVolumeMounts:
  - name: ca-volume
    mountPath: /etc/ssl/certs/lumi-root-ca.crt
    subPath: root_ca.crt
    readOnly: true