apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-ca
  namespace: step-ca
spec:
  releaseName: step-ca
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: step-certificates
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: step-ca
      interval: 1h
  values:
    fullnameOverride: step-ca

    ca:
      name: Lumi

    existingSecrets:
      enabled: true
      ca: true
      issuer: false
      certsAsSecret: true
      configAsSecret: true
      sshHostCa: false
      sshUserCa: false

    bootstrap:
      secrets: false
      enabled: false
      configmaps: false

    inject:
      enabled: false
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  wait: true