apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-ca
  namespace: step-ca
spec:
  releaseName: step-ca
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: step-certificates
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: step-ca
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: step-ca-values
      valuesKey: values.yaml
    - kind: Secret
      name: authority
      valuesKey: root-ca
      targetPath: inject.certificates.root_ca
    - kind: Secret
      name: authority
      valuesKey: root-ca-key
      targetPath: inject.secrets.x509.root_ca_key
    - kind: Secret
      name: authority
      valuesKey: intermediate-ca-key
      targetPath: inject.secrets.x509.intermediate_ca_key
    - kind: Secret
      name: authority
      valuesKey: password
      targetPath: inject.secrets.ca_password