apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocket
resources:
  - ./config/env.yaml
  # - ./resources/namespace.yaml
  # - ./resources/release.yaml
  # - ./resources/ingress.yaml
  # - ./resources/service.yaml
  # - ./resources/stateful-set.yaml
